name: Feature Request
description: Suggest a new feature or improvement
title: "[Feature]: "
labels: ["enhancement"]
body:
  - type: textarea
    id: description
    attributes:
      label: Feature Description
      description: What feature would you like to see?
      placeholder: Describe the feature or improvement you'd like to request...
    validations:
      required: true

  - type: textarea
    id: why_needed
    attributes:
      label: Why Is This Needed?
      description: Tell us what problem this feature would solve or why you need it.
      placeholder: Explain the problem or use case this feature would address...
    validations:
      required: true

  - type: textarea
    id: suggested_solutions
    attributes:
      label: Suggested Solutions
      description: If you want, share any ideas on how this feature could be implemented.
      placeholder: Share any implementation ideas, alternatives, or approaches you've considered...
    validations:
      required: false

  - type: textarea
    id: extra
    attributes:
      label: Additional Information
      description: Add any relevant screenshots, links, or resources.
      placeholder: Include mockups, examples from other apps, links, screenshots, or any other relevant information...
    validations:
      required: false
